### ISSUE TITLE
giu and goroutines

### ISSUE THREAD

**Issue by bezrazli4n0** [AllenDang/giu#33]
Hello, i have checked example about updating variables from another goroutine, but if i moving the window no gui update happen.

**Comment by AllenDang** [comment]
@bezrazli4n0 It should be fixed now. Can you help to test it?

**Comment by bezrazli4n0** [comment]
> 
> 
> @bezrazli4n0 It should be fixed now. Can you help to test it?

No, not fixed. 
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/56516965/77033610-c5b39100-69b8-11ea-9be6-b8c1340794d7.gif)

**Comment by AllenDang** [comment]
@bezrazli4n0 Can you tell me more detail about your case?

**Comment by bezrazli4n0** [comment]
> @bezrazli4n0 Can you tell me more detail about your case?

I want the value to change as the window moves. [This](https://github.com/AllenDang/giu/blob/master/examples/update/update.go) sample not working when i move the window.

**Comment by AllenDang** [comment]
@bezrazli4n0 I just tested on MacOS and Windows, it works. Maybe there is a lag that you are not getting the newest code from main branch.

**Comment by bezrazli4n0** [comment]
> @bezrazli4n0 I just tested on MacOS and Windows, it works. Maybe there is a lag that you are not getting the newest code from main branch.

Maybe. I test that code on windows 10 pro.

**Comment by AllenDang** [comment]
@bezrazli4n0 This is a bug of GLFW 3.3... The Window.PosChange event doesn't work on Windows.
